# Generated by Django 5.1.1 on 2024-09-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_student_birth_year_student_course_student_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='birth_year',
            field=models.IntegerField(default=1980),
            preserve_default=False,
        ),
    ]
