# Generated by Django 5.1.1 on 2024-09-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_instructor_birth_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
    ]
