# Generated by Django 5.1.1 on 2024-09-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_instructor_has_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
